### PR TITLE
Add new modules

### PR DESCRIPTION
**Pull request by mccanney**
Add the following modules:
- CloudWatch
- EKS
- RDS
- Resource Groups Tagging API

Fix minor typos

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Vlatombe** [comment]
Thanks! This allowed me to spot a typo in the instructions, so added it to your PR.

Do you have plans to publish a plugin leveraging these APIs?

**Comment by mccanney** [comment]
Ah, I see the issue!  I should have looked more closely. 😀 

My employer has some custom Groovy classes reaching out to AWS, it's fairly niche and specific to our requirements so it's unlikely to be of any use to anyone else.

**Comment by Vlatombe** [comment]
> some custom Groovy classes

Why do you run these in the Jenkins runtime? It is not recommended to run anything other than pipeline logic as part of the Jenkinsfile. Prefer using a separate (groovy) process running in the agent instead.

**Comment by davidmccanney** [comment]
Doesn't anything inside a `script` tag only run on the controller though?  I'd definitely be interested to see some docs if there's a better way for us to do things!

**Comment by Vlatombe** [comment]
See https://www.jenkins.io/doc/book/pipeline/pipeline-best-practices/#making-sure-to-use-groovy-code-in-pipelines-as-glue

Typically in your case, you could just use standalone `.groovy` scripts, grabbing necessary aws modules as dependencies.
Then in your pipeline, have simply
```
sh 'groovy myscript.groovy'
```
to call your logic.

**Comment by Vlatombe** [comment]
I'm not going to do this, as it would encourage improper usage of groovy within Jenkins.

This plugin is really meant for other plugins to consume, not user-level groovy scripting.

**Pull request closed without merging**
