### PR TITLE
Switch to dependency on jackson2-api to reduce conflicts

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
:bee: assuming it doesn't cause issues in other places.

**Comment by stephenc** [comment]
Well I'll put it this way, if you don't do this then you are at a random chance which version of jackson2 you get on your classpath due to the random ordering of classpath loading... so this will at least give you a consistent version... and if you cannot handle the latest version then you should be shading it in...

**Comment by cyrille-leclerc** [comment]
@stephenc would you recommend to all the plugin that depend on aws-java-sdk-plugin to update as soon as possible? Or do we have time?

**Comment by stephenc** [comment]
@cyrille-leclerc yes

**Comment by stephenc** [comment]
@reviewbybees done

**Pull request merged**
