### PR TITLE
Enable automatic release on merge to master

### PR DESCRIPTION
**Pull request by Vlatombe**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jglick** [comment]
@Vlatombe you forgot to delete `.github/workflows/release-drafter.yml`

**Comment by Vlatombe** [comment]
@jglick https://www.jenkins.io/doc/developer/publishing/releasing-cd/ step 4. is contradictory. It both says to delete and create `release-drafter.yml`

**Comment by Vlatombe** [comment]
🤦  I see. I got confused because both files had the same name and with word wrap in the documentation one set of tired eyes can easily mix them.

Could be slightly clearer with 2 steps:

4. Create or update `.github/release-drafter.yml` to contain only:
```
_extends: .github
```

5. Delete `.github/workflows/release-drafter.yml` if you previously enabled release drafter using the GitHub action, or remove the app from the repository if it was configured that way.

**Comment by jglick** [comment]
Please feel free to https://github.com/jenkins-infra/jenkins.io/edit/master/content//doc/developer/publishing/releasing-cd.adoc to make this clearer to your eyes.

**Comment by Vlatombe** [comment]
https://github.com/jenkins-infra/jenkins.io/pull/4961/

**Pull request merged**
