### PR TITLE
Add Secrets Manager SDK plugin

### PR DESCRIPTION
**Pull request by chriskilding**
Add the Secrets Manager SDK module as a plugin.

### CODE REVIEW

**Comment by chriskilding** [comment]
If merged, I'll follow this up with a PR to add it to the BOM

**Comment by chriskilding** [comment]
@Vlatombe please could you take a look at this?

**Comment by Vlatombe** [comment]
Thanks. I presume https://github.com/jenkinsci/aws-secrets-manager-secret-source-plugin will use this?

**Review by Vlatombe — APPROVED** [review]

**Comment by chriskilding** [comment]
Yep, that plugin and its counterpart SecretSource plugin will use this

**Comment by chriskilding** [comment]
@Vlatombe would you be able to do a new release build of this plugin? I think that's needed to use the new SDK module in downstream projects.

**Pull request merged**
